""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"   Filename: .vimrc                                                         "
" Maintainer: Ibrahim Ahmed <abeahmed2@gmail.com>                            "
"        URL: http://github.com/atbe/dotfiles                                "
"                                                                            "
"                                                                            "
" Sections:                                                                  "
"   01. General ................. General Vim behavior                       "
"   02. Vundle/Pathogen .................. Setup Vundle&Pathogen             "
"   03. Plugin Mods ............. Modifications made to plugins              "
"   04. Keymapping ............. All the different key mappings              "
"   05. Colorscheme ............. Colorscheme configurations                 "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" 01. General                                                                "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set nocompatible                               " be iMproved, required
filetype off                                   " required
set number                                     " Set line numbers on by default.
syntax on                                      " Set Syntax on by default.
set t_Co=256                                   " Make the colors purty.
set ls=2                                       " Show full file path always
set tabstop=4 tabstop=4 shiftwidth=4 expandtab " tabs as spaces, all size 4
set mouse=a                                    " Turn that mouse on
set shell=/bin/bash                            " Needed to keep Vundle behaved
set autochdir                                  " Always set PWD to file directory
set backspace=2                                " make backspace work like most other apps
set wildignore+=*/tmp/*,*.so,*.swp,*.zip       " MacOSX/Linux
"set relativenumber                            " o man.
set history=100                                " what can I say, I like to undo
set undolevels=100                             " what can I say, I like to undo
set showcmd                                    " Shows command at the bottom right

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" 02. vim-plug                                                               "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Specify a directory for plugins (for Neovim: ~/.local/share/nvim/plugged)
call plug#begin('~/.vim/plugged')

" vim-airline https://github.com/vim-airline/vim-airline
Plug 'vim-airline/vim-airline'
"
" vim-airline-themes https://github.com/vim-airline/vim-airline-themes
Plug 'vim-airline/vim-airline-themes'
"
" https://github.com/Shougo/deoplete.nvim
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
"
" indentline https://github.com/Yggdroot/indentLine
Plug 'yggdroot/indentline'
"
" The NERD Commenter https://github.com/scrooloose/nerdcommenter
Plug 'scrooloose/nerdcommenter'
"
" rename
Plug 'danro/rename.vim'
"
" trailing whitespace
Plug 'ntpeters/vim-better-whitespace'
"
" ctrlp /thisislife
Plug 'ctrlpvim/ctrlp.vim'
"
" tabular
Plug 'godlygeek/tabular'
"
" gitgutter
Plug 'airblade/vim-gitgutter'
"
" vim gogogo
Plug 'fatih/vim-go'
"
" base16
Plug 'chriskempson/base16-vim'
"
" doxygen doc generation support
Plug 'DoxygenToolkit.vim'
"
" neomake
Plug 'neomake/neomake'

" Initialize plugin system
call plug#end()

filetype plugin indent on    " required
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" 03. Plugin Mods                                                            "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Airline Configuration
let g:airline#extensions#tabline#enabled = 1 " Enable the list of buffers
let g:airline#extensions#tabline#fnamemod = ':t' " Show just the filename
let g:airline#extensions#branch#enabled = 1 " Enable branches
let g:airline_theme='base16'
set laststatus=2                    " Always show status bar

" YCM
let g:ycm_global_ycm_extra_conf = "~/.vim/bundle/youcompleteme/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py"
"let g:loaded_youcompleteme = 1

" base16
let base16colorspace=256  " Access colors present in 256 colorspace

" ctrlp config
let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_switch_buffer = 'Et'

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" 04. Keymapping                                                             "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
inoremap <silent> <Bar>   <Bar><Esc>:call <SID>align()<CR>a

let mapleader="\<space>"           " much more egnomic leader
" " easier write
nmap <leader>w :w!<cr>
" easier quit
nmap <leader>q :q<cr>}"

' tabularize
function! s:align()
  let p = '^\s*|\s.*\s|\s*$'
  if exists(':Tabularize') && getline('.') =~# '^\s*|' && (getline(line('.')-1) =~# p || getline(line('.')+1) =~# p)
    let column = strlen(substitute(getline('.')[0:col('.')],'[^|]','','g'))
    let position = strlen(matchstr(getline('.')[0:col('.')],'.*|\s*\zs.*'))
    Tabularize/|/l1
    normal! 0
    call search(repeat('[^|]*|',column).'\s\{-\}'.repeat('.',position),'ce',line('.'))
  endif
endfunction

" Tab Managment Settings
nnoremap th  :tabfirst<CR>
nnoremap tk  :tabnext<CR>
nnoremap tj  :tabprev<CR>
nnoremap tl  :tablast<CR>
nnoremap tt  :tabedit<Space>
nnoremap tn  :tabnew<Space>
nnoremap tm  :tabm<Space>
nnoremap td  :tabclose<CR>

" force myself to use hjkl
nnoremap <up>    <nop>
nnoremap <down>  <nop>
nnoremap <left>  <nop>
nnoremap <right> <nop>
inoremap <up>    <nop>
inoremap <down>  <nop>
inoremap <left>  <nop>
inoremap <right> <nop>

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" 05. ColorScheme                                                            "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
colorscheme base16-default-dark
set background=dark

" shell background?
if filereadable(expand("~/.vimrc_background"))
  let base16colorspace=256
  source ~/.vimrc_background
endif

" customize the colorscheme
highlight Comment ctermfg=white " comments are unreadable otherwise
hi MatchParen cterm=none ctermbg=white ctermfg=red " braces are almost hidden otherwise
