""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"   Filename: .vimrc                                                         "
" Maintainer: Ibrahim Ahmed <abeahmed2@gmail.com>                            "
"        URL: http://github.com/atbe/dotfiles                                "
"                                                                            "
"                                                                            "
" Sections:                                                                  "
"   01. General ................. General Vim behavior                       "
"   02. Vundle/Pathogen .................. Setup Vundle&Pathogen             "
"   03. Plugin Mods ............. Modifications made to plugins              "
"   04. Keymapping ............. All the different key mappings              "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" 01. General                                                                "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set nocompatible              " be iMproved, required
filetype off                  " required
set number	        	        " Set line numbers on by default.
syntax on		                  " Set Syntax on by default.
set t_Co=256                  " Make the colors purty.
set ls=2		                  " Show full file path always
set tabstop=2 shiftwidth=2 expandtab
set mouse=a                       " Turn that mouse on
set shell=/bin/bash               " Needed to keep Vundle behaved
set autochdir                     " Always set PWD to file directory
let $PATH = '/usr/local/bin:'.$PATH
set backspace=2                   " make backspace work like most other apps
set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux
let g:ctrlp_working_path_mode = 'ra'
set conceallevel=0
let g:ctrlp_switch_buffer = 'Et'

set showmatch
set matchtime=3
let mapleader = ","

" cse 320 stuff
set term=xterm-color
set textwidth=80
set wrap
set showcmd
set ruler
set cindent
set softtabstop=2
autocmd FileType  make      setlocal noexpandtab
autocmd FileType  makefile  setlocal noexpandtab


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" 02. Vundle and Pathogen                                                    "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Pathogen first because it is a really short setup lol
runtime bundle/vim-pathogen/autoload/pathogen.vim
" Where we put our self-maintained plugins
execute pathogen#infect('bundle/{}', '~/prams/vim/bundle/{}')

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

Plugin 'VundleVim/Vundle.vim'
" Vundle Packages: "
" vim-airline
Plugin 'bling/vim-airline'
" vim-airline-themes
Plugin 'vim-airline/vim-airline-themes'
" YCm
"Plugin 'valloric/youcompleteme'
" indentline
Plugin 'yggdroot/indentline'
" The NERD Commenter
Plugin 'scrooloose/nerdcommenter'
" obsession
Plugin 'tpope/vim-obsession'
" EasyMotion
" vim-slim
Plugin 'slim-template/vim-slim'
" rename
Plugin 'danro/rename.vim'
" trailing whitespace
Plugin 'bronson/vim-trailing-whitespace'
" ctrlp ... omg/thisislife
Plugin 'kien/ctrlp.vim'
" tabular
Plugin 'godlygeek/tabular'
" vim markdown
Plugin 'plasticboy/vim-markdown'
" gitgutter
Plugin 'airblade/vim-gitgutter'
" syntasticccc
"Plugin 'scrooloose/syntastic'
" base-16
Plugin 'chriskempson/base16-vim'
" doxygen doc generation support
Plugin 'DoxygenToolkit.vim'
call vundle#end()            " required
filetype plugin indent on    " required

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" 03. Plugin Mods                                                            "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" airline
let g:airline_theme='molokai'       " Set theme to JellyBeans
set laststatus=2                       " Always show status bar
" YCM
let g:ycm_global_ycm_extra_conf = "~/prams/vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py"
" javacomplete
autocmd FileType java setlocal omnifunc=javacomplete#Complete
" jedi-vim open definitions in new tabs
let g:jedi#use_tabs_not_buffers = 1

" syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" 04. Keymapping                                                             "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Tab Managment Settings
nnoremap th  :tabfirst<CR>
nnoremap tk  :tabnext<CR>
nnoremap tj  :tabprev<CR>
nnoremap tl  :tablast<CR>
nnoremap tt  :tabedit<Space>
nnoremap tn  :tabnew<Space>
nnoremap tm  :tabm<Space>
nnoremap td  :tabclose<CR>

map <F8> : !gcc % && ./a.out <CR>   " f8 compile and run c program

" use base16 background helper if possible
if filereadable(expand("~/.vimrc_background"))
  let base16colorspace=256
  source ~/.vimrc_background
endif

colorscheme base16-google-light
"set background=dark
